version: '3.8'
services:
  chrome:
    image: selenium/standalone-chrome:4.3.0
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4441:4444"
      - "7901:7900"
      - "5900:5900"